version: 2
models:
- name: orders
  columns:
  - name: order_id
    tests:
    - not_null
    - unique
  - name: order_status
    tests:
    - accepted_values:
        values:
        - completed
        - pending
        - cancelled
  - name: customer_id
    tests:
    - relationships:
        field: customer_id
        to: ref('customers')
- name: customers
  columns:
  - name: customer_id
    tests:
    - not_null
    - unique
  - name: customer_name
    tests:
    - not_null
- name: products
  columns:
  - name: product_id
    tests:
    - not_null
    - unique
  - name: product_category
    tests:
    - accepted_values:
        values:
        - electronics
        - clothing
        - food
